#! /usr/bin/env python3

import shutil
import tempfile
from pathlib import Path

import litgen

LITGEN_USE_NANOBIND = True


def my_litgen_options() -> litgen.LitgenOptions:
    # configure your options here
    options = litgen.LitgenOptions()
    options.bind_library = litgen.BindLibraryType.nanobind

    # ///////////////////////////////////////////////////////////////////
    #  Root namespace
    # ///////////////////////////////////////////////////////////////////
    # The namespace pacer is the C++ root namespace for the generated bindings
    # (i.e. no submodule will be generated for it in the python bindings)
    options.namespaces_root = ["pacer"]

    # //////////////////////////////////////////////////////////////////
    # Basic functions bindings
    # ////////////////////////////////////////////////////////////////////
    # No specific option is needed for these basic bindings
    # litgen will add the docstrings automatically in the python bindings

    # //////////////////////////////////////////////////////////////////
    # Classes and structs bindings
    # //////////////////////////////////////////////////////////////////
    # No specific option is needed for these bindings.
    # - Litgen will automatically add a default constructor with named parameters
    #   for structs that have no constructor defined in C++.
    #  - A class will publish only its public methods and members
    #
    # ...but its defaults must not be INSTANCES. By default that constructor declares
    # `Segment(first = Point(), second = Point())`, `Sectors(start_line = Segment())`,
    # `Laps(sectors = Sectors())` and `PointInTime_GPSSample(point = GPSSample())`, and nanobind
    # keeps each default as a live object inside its function for the life of the process. A
    # default that is an instance closes a type -> __init__ -> instance -> type cycle Python cannot
    # collect, so a bare `import pacer` ended with "nanobind: leaked 3 instances / 4 types / 39
    # functions" at exit (nanobind's docs, refleaks.rst "Default arguments"; measured 2026-09-24).
    # This makes those parameters `X | None = None` and builds the default in C++ on each call,
    # which is litgen's recommended nanobind setting. Calls with no argument, a positional or a
    # keyword are unchanged; tests/test_clean_shutdown.py holds the import to a silent exit.
    options.fn_params_adapt_mutable_param_with_default_value__to_autogenerated_named_ctor = True

    # ////////////////////////////////////////////////////////////////////
    # Override virtual methods in python
    # ////////////////////////////////////////////////////////////////////
    # RawGPSSource is an abstract base whose virtual methods can be overridden
    # from python (used to feed synthetic / test GPS sources into the engine).
    options.class_override_virtual_methods_in_python__regex = "^RawGPSSource$"

    # ////////////////////////////////////////////////////////////////////
    # Template specializations / ignores for the real pacer types
    # ////////////////////////////////////////////////////////////////////
    # PointInTime<GPSSample> is the only instantiation we expose.
    options.class_template_options.add_specialization("PointInTime", ["GPSSample"])

    # The CRTP operator-mixin bases (ops.hpp) are implementation detail, not API.
    options.class_template_options.add_ignore("VectorOperators")
    options.class_template_options.add_ignore("PointwiseOperators")
    options.class_template_options.add_ignore("LinearOperators")

    # NOTE: `Split` (geometry.hpp) is a function template over PointInTime<P> with no
    # registered specialization, so litgen skips it on its own — expect one benign
    # "Excluding template type PointInTime<P>" warning per regen. fn_template_options
    # ignores can NOT silence it (verified: adding add_ignore("Split") changes nothing),
    # and the former add_ignore("Interpolate"/"ToPoint") lines here were no-ops too —
    # those are plain overloads, not templates, so they were being bound anyway. They are
    # real exclusions below now.

    # Internal geometry helpers, not part of the Python API — keep them off the binding
    # surface: ApproxEqual (the single epsilon-equality used by Segment::operator==),
    # Interpolate (the crossing interpolation Split uses) and the ToPoint local-space
    # coordinate shims. ToLonLat stays bound (the deliberately-named degrees->Point API).
    #
    # Segment::Intersects is excluded for a different reason: it answers through a
    # `double *ratio` OUT-PARAMETER, and litgen binds that as a by-value `float` argument.
    # The call then type-checks, returns the right bool, writes the crossing fraction into a
    # temporary and drops it — `seg.intersects(a, b, 0.0)` returned True with the caller's
    # 0.0 untouched where the answer was 0.25. A binding that looks like it works and
    # silently loses its output is worse than none. `Segment::IntersectionRatio` (same
    # arithmetic — Intersects is an adapter over it) returns std::optional<double> and binds
    # as `intersection_ratio(fst, snd) -> float | None`, which is the Python entry point.
    options.fn_exclude_by_name__regex = "^ApproxEqual$|^Interpolate$|^ToPoint$|^Intersects$"

    # GPMFSource(size_t mp4handle) adopts an already-opened gpmf-parser MP4 handle — from
    # Python a junk integer would be dereferenced as a raw pointer and segfault the process.
    # Keep it C++-only; the GPMFSource(filename) constructor remains the Python entry point.
    options.fn_exclude_by_name_and_signature = {"GPMFSource": "size_t"}

    # ////////////////////////////////////////////////////////////////////
    # Stub spelling for std::optional
    # ////////////////////////////////////////////////////////////////////
    # litgen's stock replacement renders `std::optional<T>` as `Optional[T]`, but the stub's
    # `from typing import ...` preamble lives OUTSIDE the <litgen_stub> markers (litgen
    # preserves it verbatim) and does not import `Optional` — so the first optional-returning
    # binding would leave an undefined name in the shipped stub. `T | None` is the py311+
    # spelling and needs no import at all, which removes the coupling to that preamble
    # permanently. Registered FIRST so it wins over the stock rule; the element type is still
    # mapped afterwards (`std::optional<double>` -> `double | None` -> `float | None`).
    options.type_replacements.add_first_replacement(r"\bstd::optional<(.*?)>", r"\1 | None")

    # ////////////////////////////////////////////////////////////////////
    # Format the python stubs with black
    # ////////////////////////////////////////////////////////////////////
    # Set to True if you want the stub file to be formatted with black
    options.python_run_black_formatter = True

    return options


# ////////////////////////////////////////////////////////////////////////
# Keep child sources alive for the SequentialGPSSource chain (post-write splice)
# ////////////////////////////////////////////////////////////////////////
# SequentialGPSSource(RawGPSSource* left, RawGPSSource* right) borrows both children without
# owning them. litgen has no native keep_alive option (and its postprocess hooks don't see the
# fully-assembled pydef), so after litgen writes the binding we splice the nanobind call policy
# straight into the generated constructor: tie each child's lifetime to the SequentialGPSSource
# (nanobind arg index 1 == `self`/nurse, 2 == left, 3 == right). This is defense-in-depth —
# studio/ingest.chain_sources already holds an `owners` list — so the chain still works if a
# caller drops its references to the children.
#
# The match/replacement use the exact text litgen emits into nanobind_pacer.cpp (6-space `.def`
# indent). A literal (not regex) single replace keeps the edit surgical; if litgen ever changes
# its output so this no longer matches, the splice fails loudly at regen rather than silently
# dropping the policy.
_SEQ_CTOR_BINDING = (
    "      .def(nb::init<pacer::RawGPSSource *, pacer::RawGPSSource *>(),\n"
    '          nb::arg("left"), nb::arg("right"))'
)
_SEQ_CTOR_BINDING_KEEPALIVE = (
    "      .def(nb::init<pacer::RawGPSSource *, pacer::RawGPSSource *>(),\n"
    "          nb::keep_alive<1, 2>(), nb::keep_alive<1, 3>(),\n"
    '          nb::arg("left"), nb::arg("right"))'
)


def _splice_sequential_source_keep_alive(pydef_file: Path) -> None:
    """Inject nb::keep_alive into the generated SequentialGPSSource constructor binding."""
    code = pydef_file.read_text()
    if _SEQ_CTOR_BINDING_KEEPALIVE in code:
        return  # already spliced (idempotent)
    if _SEQ_CTOR_BINDING not in code:
        raise RuntimeError(
            "SequentialGPSSource constructor binding not found in generated "
            f"{pydef_file.name}; litgen output changed — update _SEQ_CTOR_BINDING in "
            "generate-bindings.py (keep_alive was NOT applied)."
        )
    pydef_file.write_text(code.replace(_SEQ_CTOR_BINDING, _SEQ_CTOR_BINDING_KEEPALIVE, 1))


# ////////////////////////////////////////////////////////////////////////
# A field read the caller KEEPS comes back as a copy (post-write splice)
# ////////////////////////////////////////////////////////////////////////
# nanobind's def_rw getter returns rv_policy::reference_internal: a view INTO the C++ object, kept
# alive through its owner. For a value a caller stores, that is wrong twice over (X5, measured):
#   * `kept = laps.sectors.start_line` moved with every later line edit, so an undo stack or a
#     "before" snapshot built on it would hold the line it was meant to be compared with;
#   * each element of a `std::vector` field (`sector_lines`, `Lap.points`) pointed into the
#     vector's buffer, which the next assignment reuses (the kept line reads the new one) or frees
#     (it reads freed memory: (1.39e-309, 0.0, 0.0, 1.39e-309)).
# litgen has no per-member return-policy option, so the policy is spliced into exactly these
# getters (`nb::for_getter`: the setters are untouched). `laps.sectors` itself stays a view, so
# `laps.sectors.start_line = seg` still writes into the laps; a write TWO levels down
# (`laps.sectors.start_line.first = p`) now edits a copy, and nothing does that — every caller
# assigns a whole line or a whole `pacer.Sectors` (see studio/tracks.make_segment).
# tests/test_laps_bindings.py holds each of these, and fails for any `List[<bound struct>]` field
# a future header adds without joining this list.
_COPY_ON_READ = (("Lap", "points"), ("Sectors", "start_line"), ("Sectors", "sector_lines"))


def _splice_copy_on_read(pydef_file: Path) -> None:
    """Give each `_COPY_ON_READ` getter `rv_policy::copy`; fail loudly if one can't be found."""
    code = pydef_file.read_text()
    for cls, field in _COPY_ON_READ:
        head = f'.def_rw("{field}", &pacer::{cls}::{field}, '
        policy = "nb::for_getter(nb::rv_policy::copy), "
        if code.count(head + policy) == 1:
            continue  # already spliced (idempotent)
        if code.count(head) != 1:
            raise RuntimeError(
                f"{cls}::{field}'s def_rw binding not found once in generated {pydef_file.name}; "
                "litgen output changed — update _COPY_ON_READ in generate-bindings.py (the copy "
                "return policy was NOT applied)."
            )
        code = code.replace(head, head + policy, 1)
    pydef_file.write_text(code)


def autogenerate() -> None:
    """Regenerate both files, writing each one only if its bytes changed.

    litgen rewrites its outputs in place (the text between its markers; black then reformats the
    whole stub), so on unchanged headers it used to hand both files a new mtime with identical
    bytes on every build — and the rewritten nanobind_pacer.cpp was recompiled on the next one
    (HEALTH-1, 2026-09-25). It now works on copies in a temporary directory, and a real file is
    replaced only when its copy differs. The bytes are the same either way: litgen calls black
    with an explicit `black.Mode()`, so where the stub sits does not change how it is formatted."""
    repository_dir = Path(__file__).parent.parent.parent

    header_files = [
        repository_dir / "pacer/datatypes/datatypes.hpp",
        repository_dir / "pacer/geometry/geometry.hpp",
        repository_dir / "pacer/laps/laps.hpp",
        repository_dir / "pacer/gps-source/gps-source.hpp",
    ]

    output_cpp_pydef_file = repository_dir / "bindings/pacer/nanobind_pacer.cpp"
    output_stub_pyi_file = repository_dir / "bindings/pacer/pacer/__init__.pyi"

    with tempfile.TemporaryDirectory(prefix="pacer-bindings-") as scratch:
        # litgen fills the region between its markers in an EXISTING file, so each copy starts
        # from the committed one (whose hand-kept preamble it preserves).
        pydef = Path(scratch) / output_cpp_pydef_file.name
        stub = Path(scratch) / output_stub_pyi_file.name
        shutil.copyfile(output_cpp_pydef_file, pydef)
        shutil.copyfile(output_stub_pyi_file, stub)

        litgen.write_generated_code_for_files(
            options=my_litgen_options(),
            input_cpp_header_files=[str(p) for p in header_files],
            output_cpp_pydef_file=str(pydef),
            output_stub_pyi_file=str(stub),
        )

        # Post-write: add the keep_alive call policy to the SequentialGPSSource constructor binding,
        # and the copy return policy to the getters of the fields a caller keeps.
        _splice_sequential_source_keep_alive(pydef)
        _splice_copy_on_read(pydef)

        for fresh, committed in ((pydef, output_cpp_pydef_file), (stub, output_stub_pyi_file)):
            new_bytes = fresh.read_bytes()
            if committed.read_bytes() != new_bytes:
                committed.write_bytes(new_bytes)
                print(f"generate-bindings: rewrote {committed.relative_to(repository_dir)}")


if __name__ == "__main__":
    autogenerate()
